inherits = "aggressive.toml"

[rate_limiting]
initial_ratelimit = 500
ratelimit_thresholds = [
    [1_000, 1_000],
    [5_000, 2_500],
    [25_000, 9999999999999999],
]

[tx_gen_worker]
batch_size = 10_000

[network_worker]
total_connections = 20_000 # Limited by # of ephemeral ports.
tx_queue_empty_sleep_ms = 5

[workers]
tx_gen_worker_percentage = 0.2
network_worker_percentage = 0.8
